#!/usr/bin/env @bash@/bin/bash

if [[ $1 == "query" ]]; then
    device=$2
    state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")
    if [ $state == '1' ];then
    echo "on"
    else
    echo "off"
    fi
else
    device=$1
    state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")
    if [ $state == '1' ];then
    xinput --disable "$device"
    else
    xinput --enable "$device"
    fi
fi
